version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai_interview
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ai_interview
    ports:
      - '8000:8000'
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5175:80'
    depends_on:
      - backend
